cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
 path('', views.cart_detail, name='cart_detail'),
 path('add/<int:product_id>/', views.cart_add, name='cart_add'),
 path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls' , namespace='shop')),
    path('payment/', include('payment.urls', namespace='payment')), # new
    
    
    
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [
 # post views
 path('', views.product_list, name='product_list'),
 path('prod_list', views.prod_list, name='prod_list'),
#  path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
 path('create_product/', views.create_product, name='create_product'),
 path('create_category/', views.create_category, name='create_category'),
 path('update_category/<int:id>/', views.update_category, name='update_category'),
 path('delete_category/<int:id>/', views.delete_category, name='delete_category'),
 path('update_product/<int:id>/', views.update_product, name='update_product'),
 path('delete_product/<int:id>/', views.delete_product, name='delete_product'),
 path('category/', views.category_list, name='category_list'),
 path('about/', views.about, name='about'),
 path('contact/', views.contact, name='contact'),
 path('portal/', views.portal, name='portal'),
 path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
 path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']), ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.name
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])
    


class Product(models.Model):
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        self.name


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])
    
    

shop/forms.py
from django import forms
from .models import Category, Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category','name', 'image', 'description', 'price', 'available']
       


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

shop/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Product, Category
from .forms import ProductForm, CategoryForm
from django.contrib import messages
from cart.forms import CartAddProductForm
# Create your views here.



def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('shop:category_list')
    else:
        form = CategoryForm()
    return render(request, 'shop/category/create_category.html', {'form': form})


def category_list(request):
    category = Category.objects.all()
    return render(request, 'shop/category/category_list.html', {'category':category})
def update_category(request, id):
    # Fetch the object related to the passed id
    categories = get_object_or_404(Category, id = id)
    name = request.POST.get('name')
    # Pass the object as instance in form
    form = CategoryForm(request.POST or None, instance = categories) 
    # save the data from the form and redirect
    if form.is_valid():
        # slug = form.save(commit=False)
        # slug.slug = name
        form.save()
        return redirect("shop:category_list")
    return render(request, 'shop/category/update_category.html', {'form':form})


def delete_category(request, id):
    # Fetch the object related to passed id
    categories = get_object_or_404(Category, id = id)
    if request.method == 'POST':
        # delete object
        categories.delete()
        # After deleting, redirect to category listing page
        return redirect("shop:category_list")
    return render(request, 'shop/category/delete_category.html')




def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            return redirect("shop:prod_list")
    else:
        form = ProductForm()
    return render(request, 'shop/products/create_product.html', {'form': form})



def product_list(request ,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/products/list.html', {'category': category,'categories': categories,'products': products} )

def product_detail(request,   id, slug):
    products = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    return render(request,'shop/products/detail.html',{'products': products ,'cart_product_form': cart_product_form})



def about(request):
    return render(request,'shop/products/about.html')


def contact(request):
    return render(request,'shop/products/contact.html')


def portal(request):
    return render(request,'shop/products/portal.html')

def prod_list(request ,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/products/prod_list.html', {'category': category,'categories': categories,'products': products})


def update_product(request, id):
    # Fetch the object related to the passed id
    tutorials = get_object_or_404(Product, id = id)
    name = request.POST.get('name')
    # Pass the object as instance in form
    form = ProductForm(request.POST or None, instance = tutorials) 
    # save the data from the form and redirect
    if form.is_valid():
        # slug = form.save(commit=False)
        # slug.slug = name
        form.save()
        return redirect("shop:prod_list")
    return render(request, 'shop/products/update_product.html', {'form':form})


def delete_product(request, id):
    # Fetch the object related to passed id
    tutorials = get_object_or_404(Product, id = id)
    if request.method == 'POST':
        # delete object
        tutorials.delete()
        # After deleting, redirect to category listing page
        return redirect("shop:prod_list")
    return render(request, 'shop/products/delete_product.html')

shop/templates/shop/category/category_list.html
{% extends 'shop/base.html' %}

{% block content %}

<div class="row mt-5">
    <div class="col-4">
        
        <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th>S/N</th>
                <th>Category Name</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
        {% for cat in category %}
        <tr>
        <td> {{ cat.id }} </td>
        <td> {{ cat.name }} </td>
        <td> <a href="{% url 'shop:update_category' cat.id %}"><i class="fa fa-pencil" style="color:orange;"></i></a> |
            <a href="{% url 'shop:delete_category' cat.id %}"><i class="fa fa-trash" style="color: red;"></i></a> </td>
        </tr>
        {% endfor %}
</tbody>
</table>
       
       
       

    </div>

{% endblock %}

shop/templates/shop/category/create_category.html
{% extends "shop/base.html" %}
{% block content %}
<form method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

shop/templates/shop/category/delete_category.html
{% extends 'shop/base.html' %}
{% load static %}


<!-- {% block title %}
 {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %} -->


{% block content %}
<div class="container">
<div class="row">
   <div class="col-sm-4"> 

    
    <div id="bdSidebar" 
         class="d-flex flex-column  
                flex-shrink-0  
                p-3 text-white offcanvas-md offcanvas-start"> 
        <a href="#" 
           class="navbar-brand"> Products
        </a><hr> 
        <ul class="mynav nav nav-pills flex-column mb-auto"> 
            <li class="nav-item mb-1"> 
                <a href="{% url 'shop:create_category' %}" style="text-decoration: none;"> 
                    <i class="fa-regular fa-user"></i> 
                    Create Category
                </a> 
            </li> 

            <li class="nav-item mb-1"> 
                <a href="{% url 'shop:category_list' %}" style="text-decoration: none;"> 
                    <i class="fa-regular fa-bookmark"></i> 
                    Manage Category
                    <span class="notification-badge"></span> 
                </a> 
            </li> 
            <li class="nav-item mb-1"> 
                <a href="{% url 'shop:create_product' %}" style="text-decoration: none;"> 
                    <i class="fa-regular fa-newspaper"></i> 
                    Upload Products
                </a> 
            </li> 
            <li class="nav-item mb-1"> 
               
                <a href="{% url 'shop:prod_list' %}" style="text-decoration: none;"> 
                    <i class="fa-solid fa-archway"></i> 
                   Manage Products
                </a> 
            </li> 

            </ul>
    </div></div>
    <div class="col-sm-8">
        
            <div class="row mt-5">
            <div class="col-4">
                
                <form method = "post" enctype="multipart/form-data">
                    {% csrf_token %}
                   Are you sure you want to delete category ?
                    <input type="submit" value="Yes">
                    <a href="{% url 'shop:category_list'  %}">Cancel</a>
                </form>

</div>

</div>
{% endblock %}

shop/templates/shop/category/update_category.html
{% extends 'shop/base.html' %}
{% load static %}


<!-- {% block title %}
 {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %} -->


{% block content %}
<div class="container">
<div class="row">
   <div class="col-sm-4"> 

    
    <div id="bdSidebar" 
         class="d-flex flex-column  
                flex-shrink-0  
                p-3 text-white offcanvas-md offcanvas-start"> 
        <a href="#" 
           class="navbar-brand"> Products
        </a><hr> 
        <ul class="mynav nav nav-pills flex-column mb-auto"> 
            <li class="nav-item mb-1"> 
                <a href="{% url 'shop:create_category' %}" style="text-decoration: none;"> 
                    <i class="fa-regular fa-user"></i> 
                    Create Category
                </a> 
            </li> 

            <li class="nav-item mb-1"> 
                <a href="{% url 'shop:category_list' %}" style="text-decoration: none;"> 
                    <i class="fa-regular fa-bookmark"></i> 
                    Manage Category
                    <span class="notification-badge"></span> 
                </a> 
            </li> 
            <li class="nav-item mb-1"> 
                <a href="{% url 'shop:create_product' %}" style="text-decoration: none;"> 
                    <i class="fa-regular fa-newspaper"></i> 
                    Upload Products
                </a> 
            </li> 
            <li class="nav-item mb-1"> 
               
                <a href="{% url 'shop:prod_list' %}" style="text-decoration: none;"> 
                    <i class="fa-solid fa-archway"></i> 
                   Manage Products
                </a> 
            </li> 

            </ul>
    </div></div>
    <div class="col-sm-8">
        
            <div class="row mt-5">
            <div class="col-4">
                
                <form method = "post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Submit</button>
                </form>

</div>

</div>
{% endblock %}