cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
 path('', views.cart_detail, name='cart_detail'),
 path('add/<int:product_id>/', views.cart_add, name='cart_add'),
 path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls' , namespace='shop')),
    path('payment/', include('payment.urls', namespace='payment')), # new
    
    
    
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    # path('', views.payment_init, name='create'),
    path('process/', views.payment_process, name='payment_process'), #new
    path('success/', views.payment_success, name='payment_success'), #new
    path('canceled/', views.payment_canceled, name='payment_canceled'), #new
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect
import json
from django.urls import reverse
import requests
from django.conf import settings
from django.shortcuts import get_object_or_404
from orders.models import Order

# create the Paystack instance
api_key = settings.PAYSTACK_SECRET_KEY
url = settings.PAYSTACK_INITIALIZE_PAYMENT_URL

###previous code###

def payment_process(request):
    # retrive the payment_id we'd set in the djago session ealier
    order_id = request.session.get('order_id', None)
    # using the payment_id, get the database object
    order = get_object_or_404(Order, id=order_id)
    # retrive payment amount 
    amount = order.get_total_cost() * 100

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
            reverse('payment:payment_success'))
        cancel_url = request.build_absolute_uri(
            reverse('payment:payment_canceled'))

        # metadata to pass additional data that 
        # the endpoint doesn't accept naturally.
        metadata= json.dumps({"order_id":order_id,  
                              "cancel_action":cancel_url,   
                            })

        # Paystack checkout session data
        session_data = {
            'email': order.email,
            'amount': int(amount),
            'callback_url': success_url,
            'metadata': metadata
            }

        headers = {"authorization": f"Bearer {api_key}"}
        # API request to paystack server
        r = requests.post(url, headers=headers, data=session_data)
        response = r.json()
        if response["status"] == True :
            # redirect to Paystack payment form
            try:
                redirect_url = response["data"]["authorization_url"]
                return redirect(redirect_url, code=303)
            except:
                pass
        else:
            return render(request, 'payment/process.html')
    else:
        return render(request, 'payment/process.html')
    



###previous code###

def payment_success(request):
    return render(request, 'payment/success.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block content%}
<div class="container mt-3">
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
</div>
{% endblock %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}


{% block content%}
<div class="container mt-3">
    <h1>Order No. #{{ order.id }}</h1>
    <ul class="object-tools">
        <li>
            <a href="#" onclick="window.print();">
                Print payment
            </a>
        </li>
    </ul>
    <table class="table">
        <tr>
            <th>Created</th>
            <td>{{ order.created }}</td>
        </tr>
        <tr>
            <th>Customer</th>
            <td>{{ order.first_name }} {{ order.last_name }}</td>
        </tr>
        <tr>
            <th>E-mail</th>
            <td>{{ order.email }}</td>
        </tr>
        <tr>
            <th>City</th>
            <td>
                {{ order.city }}
            </td>
        </tr>
        <tr>
            <th>Total amount</th>
            <td>₦ {{ cart.get_total_price }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>{% if order.paid %}Paid{% else %}Pending payment{% endif %}</td>
        </tr>
        <tr>
            <th>Paystack payment</th>
            <td>
                {% if payment.paystack_ref %}
                    ##################
                {% endif %}
            </td>
        </tr>
    </table>
    <form action="{% url "payment:payment_process" %}" method="post">
        <input type="submit" class="btn btn-primary mt-2" value="Pay now">
        {% csrf_token %}
    </form>
</div>
{% endblock %}

payment/templates/payment/success.html
{% extends "shop/base.html" %}

{% block content%}
<div class="container mt-3">
    <h1>Your payment was successful</h1>
    <p>Your payment has been processed successfully.</p>
</div>
{% endblock %}